# Select image to use as base for your specific model
FROM pytorch/pytorch:0.4_cuda9_cudnn7

# upgrade pip
RUN pip install --upgrade pip

# Install git, dvc and dvc azure
RUN apt-get install git
RUN pip install dvc
RUN pip install dvc[azure]

# Download repository
RUN git clone https://8d9761dfe571b84463a866dd5faadc5166f5da95@github.com/jhairgallardo/car-damage-recognition-demo.git

# Copy config file 
COPY config.local /workspace/car-damage-recognition-demo/.dvc/

# Set the working directory to repo
WORKDIR /workspace/car-damage-recognition-demo

# Download models
RUN dvc pull

# Set the working directory to /demo
WORKDIR /workspace/car-damage-recognition-demo/src

# Install any needed packages specified in requirements.txt
RUN pip install -r requirements.txt
RUN conda install pytorch torchvision cudatoolkit=9.0 -c pytorch

# Make port available to the world outside this container
EXPOSE 7000 

# Define environment variable
ENV NAME World

# Docker commands to run the container
LABEL run="docker run --runtime=nvidia --name=cardamage -it -p 7011:7000 cardamageimage"

# Run app.py when the container launches
CMD ["python", "app.py"]